[package]
name = "with-diesel"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]

[dependencies]
diesel = { version = "1.1.0", features = ["sqlite"] }
diesel_migrations = { version = "1.1.0", features = ["sqlite"] }
